### ISSUE TITLE
download_cadcd.py did not work

### ISSUE THREAD

**Issue by CZCS001** [mpitropov/cadc_devkit#23]
Hello, I am currently facing error to download the cadcd dataset, let me know what is going on. Thanks!

Traceback (most recent call last):
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/Users/opt/anaconda3/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/Users/opt/anaconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/opt/anaconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in main
  File "/Users/opt/anaconda3/lib/python3.8/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users//opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/opt/anaconda3/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

**Comment by mpitropov** [comment]
Our server seems to be down right now, I'll try to get someone to restart it.

**Comment by UZIyygod** [comment]
Now it seems still doesn't work. Right?

**Comment by mpitropov** [comment]
I have not gotten a response yet

**Comment by mpitropov** [comment]
I was told it was a DHCP issue. The server is up and running again.
