### ISSUE TITLE
@SOS@: dataset can't be downloaded.

### ISSUE THREAD

**Issue by BigPotato-H** [mpitropov/cadc_devkit#41]
when i used python code or chrome browser to the  url of the dataset 
HTTP Error 502: Bad Gateway
for example, http://wiselab.uwaterloo.ca/cadcd_data/2018_03_06/calib.zip
does anyone can solve this problem?
i have used the proxy agent. 127.0.0.1:7890
neither the python code nor the chrome browser can access to the url.

**Comment by glingli** [comment]
Me too! When I use the python to download, <urlopen error [WinError 10060]>. And When I go to the chrome it respond me "wiselab.uwaterloo.ca didn’t send any data.
ERR_EMPTY_RESPONSE"

Here is the console message:
```
(D:\Support\condaEnvs\catculate) d:\Craft\Project\CADC>python download_cadcd.py F:/Backup/CADC
Downloading labeled data
2018_03_06
Traceback (most recent call last):
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 980, in send
    self.connect()
  File "D:\Support\condaEnvs\catculate\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "D:\Support\condaEnvs\catculate\lib\socket.py", line 844, in create_connection
    raise err
  File "D:\Support\condaEnvs\catculate\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Craft\Project\CADC\download_cadcd.py", line 87, in <module>
    main()
  File "d:\Craft\Project\CADC\download_cadcd.py", line 54, in main
    calib_filename = wget.download(calib_url)
  File "D:\Support\condaEnvs\catculate\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Support\condaEnvs\catculate\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by mpitropov** [comment]
I was just about to send an email to the IT department but it seems like the issue is now resolved. You should be able to download the dataset now.
