### ISSUE TITLE
Unable to download file using download_cadcd.py

### ISSUE THREAD

**Issue by voodooed** [mpitropov/cadc_devkit#43]
I am getting HTTPError: HTTP Error 403: Forbidden :

vivek@user:/DATA1/Vivek1/Canadian_Adverse_Weather_Dataset/cadc_devkit$ python3 download_cadcd.py /DATA1/Vivek1/Canadian_Adverse_Weather_Dataset/Data
Downloading labeled data
2018_03_06
Traceback (most recent call last):
  File "/DATA1/Vivek1/Canadian_Adverse_Weather_Dataset/cadc_devkit/download_cadcd.py", line 87, in <module>
    main()
  File "/DATA1/Vivek1/Canadian_Adverse_Weather_Dataset/cadc_devkit/download_cadcd.py", line 54, in main
    calib_filename = wget.download(calib_url)
  File "/home/vivek/.local/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/anaconda/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by mpitropov** [comment]
Is this still an issue? I was able to enter the URL for that calibration file and downloaded it through chrome.
```http://wiselab.uwaterloo.ca/cadcd_data/2018_03_06/calib.zip```
